---
title: "HW 2"
format: html
editor: visual
author: José Armando Melchor Soto
---

## HW 2 : Basel Accords

-   *In what year was Basel I established?*

    July **1988**

-   *How many, and what types of risk did Basel I consider?*

    Basel I considers a single one type of risk.

    -   Credit Risk

-   *What was the minimum risk capital required?*

    A banking entity should maintain 8% minimum capital adequacy ratio, based on the risks it faced

-   *How many categories of credit risk did Basel I consider?*

    5 categories of credit risk, each with different risk weight:

    -   0%
        -   cash, goverment loans
    -   10%
        -   independent from central goverment entities loans, weights are local
    -   20 %
        -   OCDE incorporated , Banks loans, accounts, receivable, etc
    -   50 %
        -   mortage loans
    -   100 %
        -   private sector, off-balance sheet as credit equivalent, etc

    The total risk is the sum of the risk weighting by the book value of each asset, it must be fulfilled that the minimum solvency ratio

------------------------------------------------------------------------

-   *In what year was Basel II established?*

    June **2004**

-   *How many, and which, were the fundamental pillars of Basel II?*

There are three fundamental pillars of Basel II , they say :

**Pillar I :** It needs minimum capital requirements , to face market , credit and operational risk

**Pillar II:** Supervision to promote best practices in risk management.

**Pillar III:** Market discipline, considers disclosure requirements to assess basic capital information, exposure and risk assessment

-   *How many, and what types of risk did Basel II consider?*

They consider 3 types of risk:

-   Credit risk

-   Operational Risk

-   Market risk

-   *What are the types of methods that were used in Basel II to measure risk?*

<!-- -->

-   **Credit risk measurement**
    -   The Standard method , based on credit risk weights:
    -   Internal method (Based on internal bank ratings):
        -   Basic (IRB)

        -   Advance (AIRB)

<!-- -->

-   **Market risk measurement**

    -   Standard method
    -   Internal models based on VaR (Value at Risk)

-   **Operation risk measurement**

    -   **Basic Indicator method**

        -   Basic indicator approach. 15 % of the income of the last three years with income greater than zero.

    -   **Standardized method**

        -   Standardized indicator approach. Divides income into 8 lines of business

    -   **Internal advanced models**

        -   It requires the accumulation of data on the losses in each of the eight lines of business

<!-- -->

-   *What are the parameters of the internal method for calculating credit risk in Basel II?*

    **The probability of default (PD)** is a credit rating measure that is\
    assigned internally with the objective of estimating the probability\
    of default (5 years)

    **Severity, loss given default, (LGD)** it is defined as the\
    percentage of the exposure at risk that is not expected to be\
    recovered in the event of default (7 years)

    **Exposure at default (EAD)** is defined as the amount of\
    outstanding debt at the time of customer default

    **Credit term (M)** effective maturity of an exposure, measured in years.

-   *What is the difference between the basic indicator approach and the standardized approach to calculate operational risk in Basel II?* 

BIA is very simple and only weakly reflects the bank’s true risk profile, whereas TSA is much more risk-sensitive but requires stronger risk-management systems and supervisory approval.

-   *Explain the differences between Basel II and Basel III*

In short: Basel II (2004) made capital more risk-sensitive using risk-weighted assets and internal models for credit, market, and operational risk but it didn’t have a leverage backstop or liquidity rules; Basel III (2010), after the crisis, raised the amount and quality of capital, added capital buffers , introduced a leverage ratio, and set global liquidity standards, so banks can withstand funding shocks.

-   *What is the principal type of risk included in Basel III? Why do you think they included it?*

The principal type of risk include in Basel III is the Liquidity Risk , I think that they included because during the global financial crisis, many banks that seemed well-capitalized still failed because they lacked stable funding and liquid assets. Basel III included liquidity risk to ensure banks could survive sudden funding shocks.
