---
title: "C 2"
format: html
editor: visual
---

# Análisis de Riesgo

## Clase 2

José Armando Melchor Soto

------------------------------------------------------------------------

## Considerations besides return

### **Dispersion:**

-   The higher the variance , the higher the risk.

### **Distribution:**

-   Right skewed; exceptionally high returns , left skewed; exceptionally low returns.

### **Kurtosis:**

-   **Letokurtic:** High degree of concentration around the central values of the variable.
-   **Mesokurtic:** Medium degree of concentration
-   **Platykurtic:** Low degree of concentration

------------------------------------------------------------------------

## Risk Classification

#### Systematic risk

Is associated with changes in the economy due to internal and external factors. This can only be reduced under some circumstances by acquiring various assets. That is because they all are in the same conditions. **NOT DIVERSIFIABLE**

-   **Economic:**
    -   Refers to the uncertainty produced on investment due to changes made in the economic situation of the company's sector.
        -   The emergence of new competitors
        -   Market innovations
        -   Change in consumer taste
-   **Political:**
    -   Is the probability that a given political event will result in losses for a given company
        -   The actions the government takes the lead to a military coup or revolution.
        -   Changes to de labor regime modify wages.
-   **Financial:**
    -   It refers to the uncertainties in financial operations derived from the volatility of the financial and credit markets.
        -   **Market risk**
            -   Risk of loss caused by price changes in an asset that negatively affect a position..
            -   The change in the price of assets can be caused by several factors, such as; market price, volatility, and correlation.
        -   **Credit risk**
            -   Credit Risk is associated with the possibility that a debtor fails to comply with its\
                obligations. It also implies that the debtor pays only partially and after the agreed\
                date.
        -   **Liquidity risk**
            -   Liquidity Risk: Potential loss caused by events that affect the ability to dispose of\
                resources and face passive obligations.
            -   Liquidity: the ability of a person or entity to meet its short-term debts by having assets\
                that are quickly convertible into cash.
        -   **Interest rate risk**
            -   The interest rate risk is the risk security ́s price with fixed interest, such as a bond, an\
                obligation, or a loan, which will be affected by the variation of interest rates in the\
                market
        -   **Currency risk**
            -   Currency Risk is associated with the fluctuation of one currency concerning another. It\
                is the probability of loss generated by the appreciation or depreciation of currencies.

#### Unsystematic risk

Is due to the company's occasioned by internal factors ; it is unique to the company and independent of economic, political , or social factors. This risk is associated with technological changes , competition , strikes , etc. **DIVERSIFIABLE OR SPECIFIC**

-   **Technological risk:**

    -   Refers to the loss caused by interruption, failure or damage derived\
        from the information systems and technological platforms that an organization has to\
        provide its ordinary services.

-   **Strategic risk:**

    -   **Operational risk**: Can be defined as the risk of loss due to failures in administrative systems, internal procedures and intentional or unintentional human errors.
        -   Fraud
        -   Theft to the company
        -   Capture Errors
    -   **Reputation Risk:** Loss due to not materializing business opportunities attributable to a lack of prestige of an institution.
    -   **Business Risk:** Originates from changes in the variables of a business plan, thus destroying its viability, including quantifiable risks such as the economic cycle and non-quantifiable risks such as changes in the behavior of market competitors or technological changes.
    -   **Loss suffered**: in the event of non-compliance by a counterparty, and it cannot be\
        legally required to comply with payment commitments.
        -   Lack of proper documents
        -   Carelessness due to the inclusion of some harmful precept
        -   Changes in legislation after the documents, were drafted
        -   Misunderstandings of the law
        -   Financial compensation to third parties

------------------------------------------------------------------------
